CREATE DATABASE Exercicio_1_4

USE Exercicio_1_4

CREATE TABLE Artistas
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
);

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	NomeEstilo VARCHAR (20) NOT NULL
);

CREATE TABLE Albuns
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista) NOT NULL,
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo),
	Titulo VARCHAR(30) NOT NULL,
	[Data] VARCHAR(20) NOT NULL,
	Ativo VARCHAR(3) NOT NULL
);


SELECT * FROM Artistas
SELECT * FROM Albuns
SELECT * FROM Estilos
